# Generated by Django 3.2.4 on 2021-06-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_anime', models.CharField(max_length=200)),
                ('n_eps', models.IntegerField()),
                ('eps_assistidos', models.IntegerField()),
                ('estado', models.CharField(max_length=100)),
                ('nota', models.FloatField()),
            ],
        ),
    ]
